// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdaG2nDV1MWfXzzA_zGygUDZS5_6dVNQ0',
    appId: '1:701188589822:web:eb49a2ec04cc989aa63daf',
    messagingSenderId: '701188589822',
    projectId: 'cinemafirebase-26d00',
    authDomain: 'cinemafirebase-26d00.firebaseapp.com',
    storageBucket: 'cinemafirebase-26d00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrgdlTTNvO_Lpdgs2gGuBG7_TnA-ExWnU',
    appId: '1:701188589822:android:c04db90f3a4ad127a63daf',
    messagingSenderId: '701188589822',
    projectId: 'cinemafirebase-26d00',
    storageBucket: 'cinemafirebase-26d00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHHQ_x_bsjfMcKJKt0OXorydaSBUkDuIM',
    appId: '1:701188589822:ios:e8d74b47fb23b3c5a63daf',
    messagingSenderId: '701188589822',
    projectId: 'cinemafirebase-26d00',
    storageBucket: 'cinemafirebase-26d00.firebasestorage.app',
    iosBundleId: 'com.example.cinemaTicketManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHHQ_x_bsjfMcKJKt0OXorydaSBUkDuIM',
    appId: '1:701188589822:ios:e8d74b47fb23b3c5a63daf',
    messagingSenderId: '701188589822',
    projectId: 'cinemafirebase-26d00',
    storageBucket: 'cinemafirebase-26d00.firebasestorage.app',
    iosBundleId: 'com.example.cinemaTicketManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdaG2nDV1MWfXzzA_zGygUDZS5_6dVNQ0',
    appId: '1:701188589822:web:9960393599030f30a63daf',
    messagingSenderId: '701188589822',
    projectId: 'cinemafirebase-26d00',
    authDomain: 'cinemafirebase-26d00.firebaseapp.com',
    storageBucket: 'cinemafirebase-26d00.firebasestorage.app',
  );
}
